spring:
  application:
    name: rently-backend
  datasource:
    url: jdbc:postgresql://postgres:5432/rently-db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB
  mail:
    host: smtp.gmail.com
    username: dawidapplication@gmail.com
    password: bxey psje urlf lzxo
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: booking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: kafka:9092
      retries: 10
  sql:
    init:
      mode: always