spring:
  application:
    name: rently-backend
  datasource:
    url: jdbc:postgresql://postgres:5432/rently-db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update