spring:
  application:
    name: rently-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/rently-db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB
  mail:
    host: smtp.gmail.com
    username: dawidapplication@gmail.com
    password: ktxk xahl aewo cqt
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sql:
    init:
      mode: always
