services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: rently-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - rently-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-cont
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
      - rently-net

  rently-app:
    image: dawidjarosinski/rently:latest
    container_name: rently-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - postgres
    restart: on-failure
    networks:
      - rently-net

networks:
  rently-net:
    driver: bridge